name: CI

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  test:
    strategy:
      matrix:
        folder: ['.', 'test']
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ matrix.folder }}
    steps:
      - name: Initialize environment
        uses: angular/dev-infra/github-actions/npm/checkout-and-setup-node@22e0407413109186075cfebf3173549d37d4f4a4
        with:
          disable-package-manager-cache: true
      - name: Setup Bazel
        uses: angular/dev-infra/github-actions/bazel/setup@22e0407413109186075cfebf3173549d37d4f4a4
      - name: Setup Bazel Remote Caching
        uses: angular/dev-infra/github-actions/bazel/configure-remote@22e0407413109186075cfebf3173549d37d4f4a4
      - name: Test
        run: pnpm bazel test //...
