name: Presubmit
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allow manual execution.
  workflow_dispatch:
jobs:
  buildifier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version: '1.24.0'
      - name: install
        run: go install github.com/bazelbuild/buildtools/buildifier@latest
      - name: check
        run: buildifier --mode=check -r .
      - name: lint
        run: buildifier --lint=warn -r .
        continue-on-error: true
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: pnpm/action-setup@eae0cfeb286e66ffb5155f1a79b90583a127a68b # v2
        with:
          version: 10.17.1
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with:
          node-version: 22.18.0
          cache: 'pnpm'
      - name: install
        run: pnpm install
      - name: check
        run: pnpm format:check
  build-and-test:
    strategy:
      matrix:
        folder: ['.', 'test']
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ matrix.folder }}
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - uses: bazel-contrib/setup-bazel@8d2cb86a3680a820c3e219597279ce3f80d17a47 # 0.15.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
      - name: Check Bazel installation
        run: |
          which bazel
          bazel version
      - name: Build
        run: bazel build //...
      - name: Test
        run: bazel test //...
